### ISSUE TITLE
there is a problem with search in database

### ISSUE THREAD

**Issue by ghost** [delatbabel/elocryptfive#10]
Hello,

First i want thanking you for making this great package.

i have a problem when want using search in my project.

i used the Elocryptfive and encrypted "postcode" column.
the result of : User:find(1) is fine and shows the decrypted values but when i want using search , example :
User::where('postcode','5555')
it doesn't do the search and don't finding the use.(the postcode is true and available in user details)

i think this is because that the Laravel "where" doesn't decrypt the values before searching in the database.

please fix this issue , thanks a lot.

**Comment by DeftNerd** [comment]
This might not be able to be fixed, as Laravel merely passes search requests like that directly to the database engine.

In your case, it would be "SELECT \* FROM users WHERE 'postcode' = '5555'"

Since the postcode field is encrypted, it won't work. I suggest doing what the author suggests at the end of the README.MD file. Instead of encryption, you should use a hashing routine. 

The SHA256 hash of 5555 is c1f330d0aff31c1c87403f1e4347bcc21aff7c179908723535f2b31723702525

So if you wanted to search for users in post code 5555, you would something like

User::where('postcode', openssl_digest($request->input('zip_search'), 'sha512'))->get();

With such predictable numbers though, it wouldn't be difficult to just hash every possible zip code to reveal what the actual values are. 

Sadly there aren't great solutions for encryption at rest and searching those values.

**Comment by delatbabel** [comment]
As per the README:

You will not be able to search on encrypted data, because it is encrypted. Comparing encrypted values would require a fixed IV which introduces security issues.

If you need to search on data then either:
- Leave it unencrypted, or
- Hash the data and search on the hash instead of the encrypted value. Use a well known hash algorithm such as SHA256.

You could store both a hashed and an encrypted value, use the hashed value for searching and retrieve the encrypted value for other uses.

**Comment by ghost** [comment]
thanks a lot for reply.

is there any way to decrypt values before using where statements ?
or create custom search that decrypts all values before searching ?

**Comment by delatbabel** [comment]
No, what you're asking is not possible. The encryption is handled inside Laravel, with only the encrypted values being passed to the database. What you are asking for, "decrypt values before using where statements" would have to be done inside the database, so can't be done.  Even if it could be done, it would be enormously time consuming because (for example) if you had 1 million encrypted rows you would have to decrypt them all to do a search.  That might take a few hours or even longer.

Use a hash, as per the README.
