### ISSUE TITLE
Password reset email

### ISSUE THREAD

**Issue by schonhose** [delatbabel/elocryptfive#19]
With the instructions in the readme I was able to get the login working using a sha256 encryption of the email address. I made a copy of the column which was encrypted by laravel so I can always get the email address.

With the current situation I cannot get the reset password feature to work. Any suggestions on this?

**Comment by delatbabel** [comment]
I think that you will need to send the password reset email in your own code rather than using the inbuilt Laravel feature. To do that you need to store both the encrypted form of the email address (which you can decrypt to send the email) and the hashed form (for logins).

Just be careful in that encrypting the email addresses in your database doesn't have any significant benefit if they are going to be stored in plain text format in your mail logs.
