### ISSUE TITLE
unpredictable decrypt behavior

### ISSUE THREAD

**Issue by ITwrx** [delatbabel/elocryptfive#7]
i'm getting seemingly random/variable decrypt behavior. 

1) some items from a table/model are decrypted while others aren't. All are in protected $encrypts array. All worked before now. No changes to elocrypt config.

2)some items from table/model are rendered as elocrypt encrypted string(not decrypted) in view while others are not rendered at all. identical @if conditions in view. both properties exist in db as longtext elocrypted string.

3) no errors in log from elocrypt or laravel.

4) changes in decrypt behavior seem to happen randomly without changes being made to app code. I even have two identical apps(identical models, DB tables, controllers and views) that are currently exibiting diffferent behavior. one works fine while the other fails to decrypt all but one field.

5)currently, elocrypt is failing to decrypt all but one property for a particular model/table. In the past it has done the opposite: decrypted all but one. never found out why. i just deleted that row and added it anew and all was fine for a while. I have no idea what is causing the breakage. This time deleting the row and re-adding didn't work. new record still has same issue.

6)Also, elocrypt doesn't seem to work with laravel's built in password reset functionality either. IOW, laravel password reset can't read elocrypted email prop/it's not being decrypted prior to laravel trying to read it.

thanks

ps. php 7.0.2-2, Laravel Framework version 5.1.28 (LTS)

**Comment by delatbabel** [comment]
Hi,

Thanks for the report.  I have Elocrypt running in production now for some time and I haven't seen any of these issues, and the test cases don't seem to indicate anything like this behaviour, but there's nothing to say that the behaviour can't be caused by some minor difference in PHP 7 or Laravel version behaviour.

> All worked before now. No changes to elocrypt config.

What changes happened between "before now" and "now" that you can identify? Elocrypt, Laravel or PHP version bump?

> some items from table/model are rendered as elocrypt encrypted string(not decrypted) in view

That seems to indicate to me that at some point the view is triggering something that is bypassing Elocrypt's access to the $attributes array which prevents the item being decrypted.  Can you perhaps send me some of the code around the view and the model where this is happening?

What happens if, instead of passing the model to the view you call $model->toArray() and pass the array to the view? Same thing or any difference?

> no errors in log from elocrypt or laravel.

Which doesn't mean you can't insert some debug code into your local copy of Elocrypt. I use a pretty unusual debug functionality (delatbabel/applog) so I haven't included my debug code in the Elocrypt library, but while I was developing this I had debug statements right through.

> I even have two identical apps(identical models, DB tables, controllers and views) that are currently exibiting diffferent behavior. one works fine while the other fails to decrypt all but one field

Spooky.

>  elocrypt doesn't seem to work with laravel's built in password reset functionality either

OK that might be something broken in the password reset functions, or something where they are somehow accessing model data in an unorthodox way (e.g. via a direct DB call).  I'll take a look.

**Comment by ITwrx** [comment]
I figured it out...I failed to convert the second app's DB fields to longtext! It works now, of course. Thanks for the help and sorry for the false positive. I thought i had checked everything... :)

**Comment by delatbabel** [comment]
Thanks anyway. I added a note in the README about this.

**Comment by yahyazini** [comment]
In my case it wasn't because of the field type but it was because I cloned my app to develop locally and the production app and the dev app didn't share the same app key which resulted in the values not getting decrypted correctly. I hope this helps someone because this made me pull my hair haha. Thanks for the awesome tool.

**Comment by delatbabel** [comment]
> In my case it wasn't because of the field type but it was because I cloned my app to develop locally and the production app and the dev app didn't share the same app key which resulted in the values not getting decrypted correctly.

Encrypt A with key X -> decrypt with key Y -> don't get A back.  That is expected behaviour.  If you could decrypt without having the original key then I would call that a critical bug.

**Comment by yahyazini** [comment]
No I was only able to decrypt when I used the original key that was used when encrypting.
