### ISSUE TITLE
Manually encrypt data so I can use Elocrypt in Auth::attempt()

### ISSUE THREAD

**Issue by yahyazini** [delatbabel/elocryptfive#9]
First of all, thanks for this awesome Trait.
I have a db where I need to encrypt the user data including the email. And when I try to do an Auth::attempt like this:

```
$auth = Auth::attempt(array(
                "email"     =>  Input::get("email"),
                "password"  =>  Input::get("password"),
), $remember);
```

It returns an error since the email doesn't get encrypted before being passed to the attempt function. Is there a way to manually encrypt it?

**Comment by delatbabel** [comment]
Yes, you can use (assuming your user class is User):

``` php
$user = new User();
$encryptedEmail = $user->encryptedAttribute(Input::get("email"));
```

**Comment by yahyazini** [comment]
Thanks for the response but this returns a different value each time so it won't match the email value saved on the DB.

**Comment by delatbabel** [comment]
Yes, you are correct. This would require a fixed IV which has security issues.  Perhaps what you need to do is to hash the email address rather than encrypt it, and then you could compare the hashes.  Or you could store both a hashed and an encrypted email address, use the hashed value for authentication and retrieve the encrypted value for other uses (e.g. sending emails).

**Comment by yahyazini** [comment]
I think that's what I'll end up doing. Again, thanks a lot for your responses and for this awesome Trait.

**Comment by delatbabel** [comment]
I have added some notes to the README under FAQ.
